# permissions for end users to edit goalsbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: goal-projects-operator
    app.kubernetes.io/managed-by: kustomize
  name: goalsbook-editor-role
rules:
- apiGroups:
  - webapp.goals.dev
  resources:
  - goalsbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.goals.dev
  resources:
  - goalsbooks/status
  verbs:
  - get
