---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.goals.dev
  resources:
  - goalsbooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.goals.dev
  resources:
  - goalsbooks/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.goals.dev
  resources:
  - goalsbooks/status
  verbs:
  - get
  - patch
  - update
