# permissions for end users to view userbooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: goal-projects-operator
    app.kubernetes.io/managed-by: kustomize
  name: userbook-viewer-role
rules:
- apiGroups:
  - webapp.goals.dev
  resources:
  - userbooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.goals.dev
  resources:
  - userbooks/status
  verbs:
  - get
